#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication decomposePar 

# Run snappy

runParallel snappyHexMesh -overwrite

# reconstruct the mesh

runApplication reconstructParMesh -constant

# Check mesh quality
runParallel checkMesh

touch case.foam

