#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

#./Allmesh

rm -r dynamicCode log.*

runApplication decomposePar

runParallel $(getApplication)

#runApplication reconstructParMesh -allRegions -constant
runApplication reconstructPar

#paraFoam -touchAll
touch case.foam
